language: python

python:
  - "3.11"
  - "3.12"
  - "3.14"

notifications:
  email: false

install:
  - travis_retry python -m pip install --upgrade pip
  - travis_retry pip install -r requirements.txt -r requirements-test.txt
  - travis_retry pip install -e .

script:
  - python -m pytest
