# Copyright 2014-2020 by Christopher C. Little.
# This file is part of Abydos.
#
# Abydos is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Abydos is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Abydos. If not, see <http://www.gnu.org/licenses/>.

"""abydos.tests.phonetic.test_phonetic_sfinxbis.

This module contains unit tests for abydos.phonetic.SfinxBis
"""

from abydos.phonetic import SfinxBis


pa = SfinxBis()

pa4 = SfinxBis(4)

def test_sfinxbis():
    """Test abydos.phonetic.SfinxBis."""
    assert pa.encode('') == ''

    # http://www.swami.se/download/18.248ad5af12aa81365338000106/TestSfinx.txt
    # cases where the gold standard gave clearly wrong values have been
    # corrected below (marked with '# wrong'
    assert pa.encode('af Sandeberg') == 'S53162'
    assert pa.encode('av Ekenstam') == '$25835'
    assert pa.encode('Da Costa') == 'K83'
    assert pa.encode('Das Neves') == 'D8,N78'
    assert pa.encode('de Besche') == 'B8'
    assert pa.encode('de la Motte') == 'M3'
    assert pa.encode('de Las Heras') == 'H68'  # wrong
    assert pa.encode('de Los Santos') == 'S538'
    assert pa.encode('del Rosario') == 'R862'
    assert pa.encode('Den Boer') == 'B6'
    assert pa.encode('Der de Kazinczy') == 'D6,K8528'  # wrong
    assert pa.encode('des Rieux') == 'R28'
    assert pa.encode('Di Luca') == 'L2'
    assert pa.encode('Do Rosario') == 'R862'
    assert pa.encode('Don Lind') == 'L53'
    assert pa.encode('Dos Santos') == 'S538'
    assert pa.encode('du Rietz') == 'R38'
    assert pa.encode('in de Betou') == 'B3'
    assert pa.encode('La Fleur') == 'F46'
    assert pa.encode('Le Grand') == 'G653'
    assert pa.encode('li Puma') == 'L,P5'
    assert pa.encode('lo Martire') == 'L,M636'
    assert pa.encode('mac Donald') == 'D543'
    assert pa.encode('mc Intosh') == '$538'
    assert pa.encode('S:t Cyr') == 'S6'
    assert pa.encode('Van Doom') == 'D5'
    assert pa.encode('Van de Peppel') == 'P14'
    assert pa.encode('Van den Berg') == 'B62'
    assert pa.encode('Van Der Kwast') == 'K783'
    assert pa.encode('von Ahn') == '$5'
    assert pa.encode('von Dem Knesebeck') == 'K5812'
    assert pa.encode('von Der Burg') == 'B62'
    assert pa.encode("D'Angelo") == 'D524'
    assert pa.encode("O'Conner") == '$256'
    assert pa.encode('Los') == 'L8'
    assert pa.encode('Mac') == 'M2'
    assert pa.encode('Till') == 'T4'
    assert pa.encode('Van') == 'V5'
    assert pa.encode('Von') == 'V5'
    assert pa.encode('Bernadotte af Wisborg') == 'B6533,V8162'
    assert pa.encode('Hjort af Ornäs') == 'J63,$658'
    assert pa.encode('Horn af Åminne') == 'H65,$55'
    assert pa.encode('Horn av Åminne') == 'H65,$55'
    assert pa.encode('Hård af Segerstad') == 'H63,S26833'
    assert pa.encode('Hård av Segerstad') == 'H63,S26833'
    assert pa.encode('Stael von Holstein') == 'S34,H48325'
    assert pa.encode('de Oliveira e Silva') == '$4726,S47'
    assert pa.encode('de Alfaro y Gómez') == '$476,G58'
    assert pa.encode('Arjaliès-de la Lande') == '$6248,L53'
    assert pa.encode('Dominicus van den Bussche') == 'D5528,B8'
    assert pa.encode('Edebol Eeg-Olofsson') == '$314,$2,$4785'
    assert pa.encode('Jonsson-Blomqvist') == 'J585,B452783'
    assert pa.encode('Kiviniemi Birgersson') == '#755,B62685'
    assert pa.encode('Massena Serpa dos Santos') == 'M85,S61,S538'
    assert pa.encode('S:t Clair Renard') == 'K426,R563'
    assert pa.encode('Skoog H Andersson') == 'S22,H,$53685'
    assert pa.encode('von Post-Skagegård') == 'P83,S22263'
    assert pa.encode('von Zur-Mühlen') == 'S6,M45'
    assert pa.encode('Waltå O:son') == 'V43,$85'
    assert pa.encode('Zardán Gómez de la Torre') == 'S635,G58,T6'
    assert pa.encode('af Jochnick') == 'J252'
    assert pa.encode('af Ioscnick') == 'J8252'
    assert pa.encode('Aabakken') == '$125'
    assert pa.encode('Åbacken') == '$125'
    assert pa.encode('Ahlen') == '$45'
    assert pa.encode('Aleen') == '$45'
    assert pa.encode('Braunerhielm') == 'B656245'
    assert pa.encode('Branneerhielm') == 'B656245'
    assert pa.encode('Carlzon') == 'K6485'
    assert pa.encode('Karlsson') == 'K6485'
    assert pa.encode('Enochsson') == '$5285'
    assert pa.encode('Ericsson') == '$6285'
    assert pa.encode('Ericksson') == '$6285'
    assert pa.encode('Erixson') == '$6285'
    assert pa.encode('Filipsson') == 'F4185'
    assert pa.encode('Philipson') == 'F4185'
    assert pa.encode('Flycht') == 'F423'
    assert pa.encode('Flygt') == 'F423'
    assert pa.encode('Flykt') == 'F423'
    assert pa.encode('Fröijer') == 'F626'
    assert pa.encode('Fröjer') == 'F626'
    assert pa.encode('Gertner') == 'J6356'
    assert pa.encode('Hiertner') == 'J6356'
    assert pa.encode('Hirch') == 'H62'
    assert pa.encode('Hirsch') == 'H68'
    assert pa.encode('Haegermarck') == 'H26562'
    assert pa.encode('Hägermark') == 'H26562'
    assert pa.encode('Isaxon') == '$8285'
    assert pa.encode('Isacsson') == '$8285'
    assert pa.encode('Joachimsson') == 'J2585'
    assert pa.encode('Joakimson') == 'J2585'
    assert pa.encode('Kjell') == '#4'
    assert pa.encode('Käll') == '#4'
    assert pa.encode('Knapp') == 'K51'
    assert pa.encode('Krans') == 'K658'
    assert pa.encode('Krantz') == 'K6538'
    assert pa.encode('Kvist') == 'K783'
    assert pa.encode('Quist') == 'K783'
    assert pa.encode('Lidbeck') == 'L312'
    assert pa.encode('Lidbäck') == 'L312'
    assert pa.encode('Linnér') == 'L56'
    assert pa.encode('Linner') == 'L56'
    assert pa.encode('Lorenzsonn') == 'L6585'
    assert pa.encode('Lorentzon') == 'L65385'
    assert pa.encode('Lorenßon') == 'L6585'
    assert pa.encode('Lyxell') == 'L284'
    assert pa.encode('Lycksell') == 'L284'
    assert pa.encode('Marcström') == 'M628365'
    assert pa.encode('Markström') == 'M628365'
    assert pa.encode('Michaelsson') == 'M2485'
    assert pa.encode('Mikaelson') == 'M2485'
    assert pa.encode('Mörch') == 'M62'
    assert pa.encode('Mörck') == 'M62'
    assert pa.encode('Mörk') == 'M62'
    assert pa.encode('Mørk') == 'M62'
    assert pa.encode('Nääs') == 'N8'
    assert pa.encode('Naess') == 'N8'
    assert pa.encode('Nordstedt') == 'N63833'
    assert pa.encode('Oxenstierna') == '$28583265'
    assert pa.encode('Palmçrañtz') == 'P4526538'
    assert pa.encode('Palmcrantz') == 'P4526538'
    assert pa.encode('Palmkrantz') == 'P4526538'
    assert pa.encode('Preuss') == 'P68'
    assert pa.encode('Preutz') == 'P638'
    assert pa.encode('Richardson') == 'R26385'
    assert pa.encode('Rikardson') == 'R26385'
    assert pa.encode('Ruuth') == 'R3'
    assert pa.encode('Ruth') == 'R3'
    assert pa.encode('Sæter') == 'S36'
    assert pa.encode('Zäter') == 'S36'
    assert pa.encode('Schedin') == '#35'
    assert pa.encode('Sjödin') == '#35'
    assert pa.encode('Siöö') == '#'
    assert pa.encode('Sjöh') == '#'
    assert pa.encode('Svedberg') == 'S73162'
    assert pa.encode('Zwedberg') == 'S73162'
    assert pa.encode('Tjäder') == '#36'
    assert pa.encode('þornquist') == 'T652783'
    assert pa.encode('Thörnqvist') == 'T652783'
    assert pa.encode('Törnkvist') == 'T652783'
    assert pa.encode('Wichman') == 'V255'
    assert pa.encode('Wickman') == 'V255'
    assert pa.encode('Wictorin') == 'V2365'
    assert pa.encode('Wictorsson') == 'V23685'
    assert pa.encode('Viktorson') == 'V23685'
    assert pa.encode('Zachrisson') == 'S2685'
    assert pa.encode('Zakrison') == 'S2685'
    assert pa.encode('Övragård') == '$76263'
    assert pa.encode('Öfvragårdh') == '$76263'
    assert pa.encode('Bogdanovic') == 'B23572'
    assert pa.encode('Bogdanovitch') == 'B235732'
    assert pa.encode('Dieterich') == 'D362'
    assert pa.encode('Eichorn') == '$265'
    assert pa.encode('Friedrich') == 'F6362'
    assert pa.encode('Grantcharova') == 'G653267'
    assert pa.encode('Ilichev') == '$427'
    assert pa.encode('Ivankovic') == '$75272'
    assert pa.encode('Ivangurich') == '$75262'
    assert pa.encode('Kinch') == '#52'
    assert pa.encode('Kirchmann') == '#6255'
    assert pa.encode('Machado') == 'M23'
    assert pa.encode('Reich') == 'R2'
    assert pa.encode('Roche') == 'R2'
    assert pa.encode('Rubaszkin') == 'R1825'
    assert pa.encode('Rubaschkin') == 'R1825'
    assert pa.encode('Sanchez') == 'S528'
    assert pa.encode('Walukiewicz') == 'V42728'
    assert pa.encode('Valukievitch') == 'V42732'
    assert pa.encode('K') == 'K'
    assert pa.encode('2010') == ''
    assert pa.encode('cese') == 'S8'

    # a few max_length tests
    assert SfinxBis(3).encode('Kiviniemi Birgersson') == '#75,B62'
    assert pa4.encode('Eichorn') == '$265'
    assert pa4.encode('Friedrich') == 'F636'
    assert pa4.encode('Grantcharova') == 'G653'
    assert pa4.encode('Ilichev') == '$427'
    assert pa4.encode('Ivankovic') == '$752'
    assert pa4.encode('Ivangurich') == '$752'
    assert pa4.encode('Kinch') == '#52'
    assert pa4.encode('Kirchmann') == '#625'
    assert pa4.encode('Machado') == 'M23'
    assert pa4.encode('Reich') == 'R2'
    assert pa4.encode('Roche') == 'R2'
    assert pa4.encode('Rubaszkin') == 'R182'
    assert pa4.encode('Rubaschkin') == 'R182'
    assert pa4.encode('Sanchez') == 'S528'
    assert pa4.encode('Walukiewicz') == 'V427'
    assert pa4.encode('Valukievitch') == 'V427'
    assert pa4.encode('K') == 'K'
    assert pa4.encode('2010') == ''
    assert pa4.encode('cese') == 'S8'

    # etc. (for code coverage)
    assert pa.encode('chans') == '#58'
    assert pa.encode('ljud') == 'J3'
    assert pa.encode('qi') == 'K'
    assert pa.encode('xavier') == 'S76'
    assert pa.encode('skjul') == '#4'
    assert pa.encode('schul') == '#4'
    assert pa.encode('skil') == '#4'

    # max_length bounds tests
    assert SfinxBis(max_length=-1).encode('Niall') == 'N4'
    assert SfinxBis(max_length=0).encode('Niall') == 'N4'

    # encode_alpha
    assert pa.encode_alpha('Stael von Holstein') == 'STL,HLSTKN'
    assert pa.encode_alpha('de Oliveira e Silva') == '$LFKR,SLF'
    assert pa.encode_alpha('de Alfaro y Gómez') == '$LFR,GNS'
    assert pa.encode_alpha('Arjaliès-de la Lande') == '$RKLS,LNT'
